#!/usr/bin/env perl
use strict;
use warnings;

use FindBin;
FindBin::again();
use lib "$FindBin::Bin/lib";
use Snapshot;

FindBin::again();
my $bin_dir = "$FindBin::Bin";

my $backup_base_dir = Snapshot::init_backup_base_dir($bin_dir);
my %config = Snapshot::read_config ($bin_dir);

my $interval = Snapshot::calc_interval($config{backup_interval});
unless ($interval) {
    die "Could not determine a backup interval.\n";
}

if (needs_backup ($backup_base_dir, $interval)) {
    `"$bin_dir/mksnapshot"`;
}

sub needs_backup {
    my ($backup_base_dir, $interval) = @_;

    my $last     = last_backup_seconds($backup_base_dir);
    my $current  = time();

    return ( $last + $interval < $current) ;
}

sub last_backup_seconds {
    my ($backup_base_dir) = @_;

    my $seconds = 0;
    my $last_good = Snapshot::read_last_good($backup_base_dir);
    if ( $last_good ) {
        ($seconds) = (split /\./, $last_good)[-1];
    }
    return $seconds;
}
